main: net.Invify.inventory.InvifyAPI
version: 1.0
name: invify-lib
author: fzzgg
api-version: 1.13
description: >
  InvifyLib is a powerful and feature-rich library designed for developers
  to create custom GUIs with ease.