main: net.invifi.inventory.InvifiAPI
version: 1.0
name: invifi-lib
author: fzzgg
api-version: 1.13
description: >
  InvifiLib is a powerful and feature-rich library designed for developers
  to create custom GUIs with ease. Packed with advanced
  features and high flexibility, it simplifies the process of building and managing
  interactive menus in Minecraft. (Still in developing :>)